# Generated by Django 4.2.7 on 2025-10-23 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillnft',
            options={'ordering': ['-issued_at'], 'verbose_name': 'NFT Навык', 'verbose_name_plural': 'NFT Навыки'},
        ),
        migrations.AlterField(
            model_name='skillnft',
            name='description',
            field=models.TextField(verbose_name='Описание навыка'),
        ),
        migrations.AlterField(
            model_name='skillnft',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата выпуска'),
        ),
        migrations.AlterField(
            model_name='skillnft',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='skillnft',
            name='proof_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на доказательство'),
        ),
        migrations.AlterField(
            model_name='skillnft',
            name='skill_name',
            field=models.CharField(max_length=100, verbose_name='Название навыка'),
        ),
        migrations.AlterField(
            model_name='skillnft',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=100, verbose_name='Хэш транзакции'),
        ),
    ]
